Squash - revert - need to figure out how to move try/catch to higher level
attempts to do so thus far have resulted in actual:
java.lang.IllegalArgumentException: No implementation of method:
:register-ns of protocol: #'kr.core.rdf/rdfKB found for class: nil